require: rubocop-performance

AllCops:
  Exclude:
    - config/initializers/devise.rb
    - bin/*
    - Gemfile
    - db/schema.rb
    - db/migrate/*

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 30

Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false
