default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials.postgresql[:username] %>
  password: <%= Rails.application.credentials.postgresql[:password] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: lightsoft_develop

test:
  <<: *default
  database: lightsoft_test
